sudo: required

language: cpp

compiler: g++

before_scirpt:
  - cd ../
  - wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz
  - tar -zxvf cmake-3.10.2-Linux-x86_64.tar.gz
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar -zxvf release-1.10.0.tar.gz
  - ls -a
  - mkdir googletest-build
  - cd googletest-build
  - sudo ../cmake-3.10.2-Linux-x86_64/bin/cmake ../googletest-release-1.10.0
  - sudo make -j5
  - sudo make install
  - cd ../
  - mkdir build-BNN
  - cd build-BNN
  - sudo ../cmake-3.10.2-Linux-x86_64/bin/cmake -DBUILD_TESTS=ON -DINSTALL_GOOGLETEST=OFF -DCMAKE_PREFIX_PATH=/usr/local/include ../BNN
  - sudo make -j5
  - wget http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
  - gzip -d t10k-images-idx3-ubyte.gz
  - wget http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
  - gzip -d t10k-labels-idx1-ubyte.gz

script:
  - ./bin/test_core
  - ./bin/test_operations
